#!/bin/bash
#PBS -q medium

#PBS -N reheaderv3
#PBS -l mem=30gb
#PBS -l walltime=4:00:00
#PBS -l procs=1

#PBS -t 1-22

#PBS -o /zfs3/users/matthew.parker/matthew.parker/PBSlogs/log_$PBS_JOBID.txt
#PBS -e /zfs3/users/matthew.parker/matthew.parker/PBSlogs/err_$PBS_JOBID.txt

echo "Changing to directory containing gwasqc."
cd /zfs3/users/matthew.parker/matthew.parker/PBSscripts/GenotypeImputation/gwasqc
echo "Starting script at `date`"

module load plink2
module load R
module load eigensoft
module load shapeit
module load impute2
module load vcftools # for vcf-sort
module load samtools
module load htslib   # for bgzip
module load bcftools

GO_Omni="/zfs3/scratch/saram_lab/PNC/data/genotypeImputed/hrc/imputed_premerge/GO_Omni/"
GO_Quad="/zfs3/scratch/saram_lab/PNC/data/genotypeImputed/hrc/imputed_premerge/GO_Quad/"
GO_v3="/zfs3/scratch/saram_lab/PNC/data/genotypeImputed/hrc/imputed_premerge/GO_v3/"
GO_v1_hg18="/zfs3/scratch/saram_lab/PNC/data/genotypeImputed/hrc/imputed_premerge/GO_v1_hg18/"

sh post_impute_reheader.sh $PBS_ARRAYID $GO_v3

echo "script completed at `date`"
